development:
  clients:
    default:
      database: backend_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: backend_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
