development:
  clients:
    default:
      uri: <%= ENV['DATABASE_URL'] %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: <%= ENV['DATABASE_URL'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
