# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  Enabled: true
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
